# workflow name
name: Hexo博客持续集成

# master branch on push, auto run
on: 
  push:
    branches:
      - master
      
jobs:
  build: 
    runs-on: ubuntu-latest
        
    steps:
    # check it to your workflow can access it
    # from: https://github.com/actions/checkout
    - name: 检出仓库代码
      uses: actions/checkout@master
      
    # from: https://github.com/actions/setup-node
    - name: 安装Node.js 11.x
      uses: actions/setup-node@master
      with:
        node-version: "11.x"
    
    - name: 安装Hexo依赖
      run: |
        npm install hexo-cli -g
        npm install

    - name: 配置部署私钥
      env:
        HEXO_DEPLOY_PRIVATE_KEY: ${{ secrets.HEXO_DEPLOY_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$HEXO_DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        
    - name: 配置GIT信息
      run: |
        git config --global user.name 'dr34-m'
        git config --global user.email '1416814478@qq.com'

    - name: 部署Hexo到Github
      run: |
        hexo clean
        hexo generate
        hexo deploy

    - name: 部署Hexo到云服务器
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./public/
