# workflow name
name: Hexo博客持续集成

# master branch on push, auto run
on: 
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    # check it to your workflow can access it
    # from: https://github.com/actions/checkout
    - name: 检出仓库代码
      uses: actions/checkout@master
      
    # from: https://github.com/actions/setup-node
    - name: 安装Node.js 11.x
      uses: actions/setup-node@master
      with:
        node-version: "11.x"
    
    - name: 安装Hexo依赖
      run: |
        npm install hexo-cli -g
        npm install

    - name: 构建Hexo
      run: |
        hexo clean
        hexo generate

    - name: 部署到云服务器
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-avzr --delete"
        SOURCE: "./public/"
        REMOTE_HOST: ${{ secrets.SERVER_HOST }}
        REMOTE_USER: ${{ secrets.SERVER_USER }}
        TARGET: "/www/wwwroot/blog.ctftools.com/"

    - name: 配置Github部署私钥
      env:
        HEXO_DEPLOY_PRIVATE_KEY: ${{ secrets.HEXO_DEPLOY_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$HEXO_DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        
    - name: 配置Git信息
      run: |
        git config --global user.name 'dr34-m'
        git config --global user.email '1416814478@qq.com'

    - name: 部署Hexo到Github
      run: hexo deploy

    - name: 打包压缩
      run: tar -zcvf release.tgz public

    - name: 发布 Release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ github.run_id }}
        release_name: Release ${{ github.run_id }}
         # 是否是草稿
        draft: false
         # 是否是预发布
        prerelease: false

    - name: 上传构建结果到 Release
      id: upload-release-asset
      uses: actions/upload-release-asset@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release.tgz
        asset_name: release.tgz
        asset_content_type: application/x-tgz

    - name: 上传到腾讯云COS并刷新CDN
      env:
        SECRET_ID: ${{ secrets.TCLOUD_API_ID }}
        SECRET_KEY: ${{ secrets.TCLOUD_API_KEY }}
        BUCKET: hexo-1252906577
        REGION: ap-nanjing
      run: |
        sudo pip install coscmd
        coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
        coscmd upload -rfs --delete ./public/ /
        sudo pip install tccli
        tccli configure set secretId $SECRET_ID
        tccli configure set secretKey $SECRET_KEY
        tccli configure set region $REGION
        tccli cdn PurgePathCache --cli-unfold-argument --Paths https://hexo.ctftools.com/ --FlushType delete